# Generated by Django 2.1 on 2018-08-25 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=20)),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50)),
                ('opisanie', models.TextField()),
                ('dlitelnost', models.FloatField()),
                ('format', models.CharField(max_length=3)),
                ('proizvodstvo', models.CharField(max_length=20)),
                ('rezhiser', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(height_field='image_height', upload_to='media/films', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='525', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='260', editable=False, null=True)),
                ('trailer', models.URLField()),
                ('prokat', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_bil', models.IntegerField(default=0)),
                ('summa', models.IntegerField(default=0)),
                ('seans_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.Seans')),
            ],
        ),
        migrations.CreateModel(
            name='Zhanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='zhanr',
            field=models.ManyToManyField(to='films.Zhanr'),
        ),
        migrations.AddField(
            model_name='bron',
            name='seans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.Seans'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='seans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.Seans'),
        ),
    ]
